export default {
  login: 'greatshah222',
  id: 25220609,
  node_id: 'MDQ6VXNlcjI1MjIwNjA5',
  avatar_url: 'https://avatars1.githubusercontent.com/u/25220609?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/greatshah222',
  html_url: 'https://github.com/greatshah222',
  followers_url: 'https://api.github.com/users/greatshah222/followers',
  following_url:
    'https://api.github.com/users/greatshah222/following{/other_user}',
  gists_url: 'https://api.github.com/users/greatshah222/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/greatshah222/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/greatshah222/subscriptions',
  organizations_url: 'https://api.github.com/users/greatshah222/orgs',
  repos_url: 'https://api.github.com/users/greatshah222/repos',
  events_url: 'https://api.github.com/users/greatshah222/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/greatshah222/received_events',
  type: 'User',
  site_admin: false,
  name: 'Bishal Shah',
  company: null,
  blog: 'bishalshah.ml',
  location: 'Finland',
  email: null,
  hireable: null,
  bio: 'Full Stack Developer',
  twitter_username: 'bishalshah',
  public_repos: 41,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2017-01-19T09:12:54Z',
  updated_at: '2020-08-09T02:38:43Z',
};
